language: java
# See: https://docs.travis-ci.com/user/languages/java#Caching
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - gradle wrapper
script:
  - ./gradlew test --stacktrace --i
