language: java
# See: https://docs.travis-ci.com/user/languages/java#Caching
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_script:
  - gradle wrapper
  - cp .travis/application.properties.example config/application.properties
  - psql -c 'create database commcarehq;' -U postgres
  - psql -c 'create database formplayer;' -U postgres
  - curl -X PUT localhost:5984/commcarehq
  - curl -X PUT localhost:5984/_config/admins/commcarehq -d '"commcarehq"'
script:
  - ./gradlew copyTestResources
  - ./gradlew test
services:
  - postgresql
  - redis-server
  - couchdb
