name: Formplayer tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: formplayer
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      MALLOC_ARENA_MAX: 1
      GRADLE_OPTS: -Xmx512m
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Setup config
        run: |
          cp .travis/application.example.properties config/application.properties
          cp .travis/travis.gradle.properties gradle.properties
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: copyTestResources
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: bootJar
      - name: "Codecov upload"
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
